### PR TITLE
OCPBUGS-26140: Fix formatting in snyk vendor exclusions

### PR DESCRIPTION
**Pull request by racheljpg**
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

### CODE REVIEW

**Comment by nrb** [comment]
Azure and GCP OVN tech preview jobs are both failing with this error:

```
{Operator degraded (AuthStatusHandler_FailedApply): AuthStatusHandlerDegraded: failed to create typed patch object (/cluster; config.openshift.io/v1, Kind=Authentication): .status.oidcClients: field not declared in schema  Operator degraded (AuthStatusHandler_FailedApply): AuthStatusHandlerDegraded: failed to create typed patch object (/cluster; config.openshift.io/v1, Kind=Authentication): .status.oidcClients: field not declared in schema}
```

That doesn't seem like a failure that's caused by this PR, but maybe it's something broken in the tech preview payload?

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-azure-ovn-techpreview

No point in running E2E for this PR

**Pull request merged**
