### PR TITLE
OCPBUGS-42612: Sync Release 4.17 with UPSTREAM

### PR DESCRIPTION
**Pull request by serngawy**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-azure-ovn-techpreview

Has the master version of this PR been tested by QE?

This image is in the 4.17 payload but isn't actually deployed in any form factor or feature set presently, so should not affect anything even if it has issues, but would still be good to get some QE sign off right?

/label backport-risk-assessed

**Comment by JoelSpeed** [comment]
@marek-veber Please stop testing the Azure check, it cannot pass, I already overrode it

/override ci/prow/e2e-azure-ovn-techpreview

**Comment by marek-veber** [comment]
@JoelSpeed - Pls. can you approve this PR, we are not included in the `OWNERS` file in the `release-4.17` branch :(

**Comment by JoelSpeed** [comment]
@marek-veber I spoke with @serngawy via slack, this cannot merge presently because of the imminent 4.17 release. I need to also speak to @sdodson about the fact that this doesn't have the regular bug backporting chain, nor any QE.

I'm awaiting Scott's response before we move forward

**Comment by marek-veber** [comment]
> @marek-veber I spoke with @serngawy via slack, this cannot merge presently because of the imminent 4.17 release. I need to also speak to @sdodson about the fact that this doesn't have the regular bug backporting chain, nor any QE.
> 
> I'm awaiting Scott's response before we move forward

Ok, thanks.

**Comment by sdodson** [comment]
I've set jira/valid-bug based on Joel having explained that this is not used in the payload today.

**Comment by serngawy** [comment]
Thanks @sdodson , we work on owning this repo with QE testing it as well. @JoelSpeed I think we can merge this PR now ?

**Comment by JoelSpeed** [comment]
Will still need to wait for staff eng approval label requirement to be removed, this should be shortly after the GA for 4.17

**Pull request merged**
